# Generated by Django 3.1.12 on 2025-11-23 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0002_auto_20251122_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_of_sessions',
            field=models.IntegerField(default=1, help_text='Número total de sesiones del plan'),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_days',
            field=models.JSONField(blank=True, default=list, help_text='Días de la semana preferidos (lista de weekdays)'),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_employee',
            field=models.ForeignKey(blank=True, help_text='Tutor o terapeuta preferido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_time',
            field=models.TimeField(blank=True, help_text='Hora preferida para las sesiones', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sessions_generated',
            field=models.BooleanField(default=False, help_text='Indica si ya se generaron las sesiones'),
        ),
    ]
