# Generated by Django 3.1.12 on 2025-11-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20251123_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(blank=True, help_text='Fecha de inicio de las sesiones', null=True),
        ),
    ]
