# Generated by Django 3.1.12 on 2025-11-23 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0004_order_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preferred_therapist',
            field=models.ForeignKey(blank=True, help_text='Terapeuta asignado para plan estudiante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapy_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_tutor',
            field=models.ForeignKey(blank=True, help_text='Tutor asignado para plan estudiante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutoring_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='therapy_sessions',
            field=models.IntegerField(default=0, help_text='Número de sesiones de terapia'),
        ),
        migrations.AddField(
            model_name='order',
            name='therapy_start_date',
            field=models.DateField(blank=True, help_text='Fecha de inicio de terapias', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='therapy_time',
            field=models.TimeField(blank=True, help_text='Hora para sesiones de terapia', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tutoring_sessions',
            field=models.IntegerField(default=0, help_text='Número de sesiones de tutoría'),
        ),
        migrations.AddField(
            model_name='order',
            name='tutoring_start_date',
            field=models.DateField(blank=True, help_text='Fecha de inicio de tutorias', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tutoring_time',
            field=models.TimeField(blank=True, help_text='Hora para sesiones de tutoría', null=True),
        ),
    ]
