# Generated by Django 3.1.12 on 2025-11-24 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_auto_20251123_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('profile_update', 'Actualización de Perfil'), ('order_created', 'Orden Creada'), ('order_updated', 'Orden Actualizada'), ('session_scheduled', 'Sesión Programada'), ('session_completed', 'Sesión Completada'), ('file_uploaded', 'Archivo Subido'), ('file_downloaded', 'Archivo Descargado'), ('other', 'Otra Acción')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(help_text='Tamaño máximo: 10MB. Formatos permitidos: documentos, imágenes, audio, video', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png', 'gif', 'mp3', 'mp4', 'zip'], message='Tipo de archivo no permitido. Extensiones permitidas: pdf, doc, docx, txt, jpg, jpeg, png, gif, mp3, mp4, zip')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration_minutes',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(15, message='La duración mínima es 15 minutos'), django.core.validators.MaxValueValidator(480, message='La duración máxima es 8 horas')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='scheduled_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programada'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No Asistió')], db_index=True, default='scheduled', max_length=50),
        ),
    ]
