# Generated by Django 3.1.12 on 2025-11-24 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_auto_20251124_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text="Formato: '+999999999' (9-15 dígitos)", max_length=50, null=True, validators=[django.core.validators.RegexValidator(message="Número de teléfono debe tener formato: '+999999999'. Entre 9 y 15 dígitos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
