# Generated by Django 3.1.12 on 2025-11-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_auto_20251124_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='number_of_sessions',
            field=models.IntegerField(default=4, help_text='Número de sesiones para servicios individuales (tutoría o terapia)'),
        ),
        migrations.AddField(
            model_name='price',
            name='therapy_sessions',
            field=models.IntegerField(default=8, help_text='Número de sesiones de terapia para Plan Estudiante'),
        ),
        migrations.AddField(
            model_name='price',
            name='tutoring_sessions',
            field=models.IntegerField(default=8, help_text='Número de sesiones de tutoría para Plan Estudiante'),
        ),
    ]
