# Generated by Django 3.1.12 on 2025-11-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_auto_20251124_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Marcar este plan para mostrarlo como destacado en la página principal', verbose_name='Plan Destacado'),
        ),
    ]
