# Generated by Django 3.1.12 on 2025-12-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='image',
            field=models.CharField(blank=True, help_text='Nombre del archivo de imagen en assets/images/', max_length=255, null=True, verbose_name='Imagen del servicio'),
        ),
    ]
