# Generated by Django 3.1.12 on 2025-12-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20251124_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('empleado', 'Empleado'), ('estudiante', 'Estudiante'), ('admin', 'Administrador'), ('tutor', 'Tutor'), ('psicologo', 'Psicólogo')], default='cliente', max_length=20),
        ),
    ]
